### PR TITLE
Added search node functionality

### PR DESCRIPTION
**Pull request by christinoleo**
I was missing the search functionality from the search bar of the "add new node dialog". It is not the most efficient implementation, but I believe it works well. Let me know if you prefer some other way.

### CODE REVIEW

**Comment by christinoleo** [comment]
I also just noticed it fixes issue #2

**Comment by HungryProton** [comment]
Thanks for the PR
Don't worry about making one PR for each separate features. Searching nodes works really well but enabling multi-input on a single slot causes more issues than it solves because of how the concept node collects its inputs and how multi-threading is setup. (Multi-threading is disabled for now though)

**Comment by christinoleo** [comment]
Ah, good to know about the multi-threading. I didn't yet try to understand that part. I guess I'll change to dynamically add a new input when the previous input is populated, though I am not sure how godot will handle that.

I will also keep in mind that to send PRs with more changes at once is better for you. 
Thank you for the feedback!

**Comment by HungryProton** [comment]
Sorry I didn't wrote my sentence properly, I meant to say it's totally fine to make on PR for each feature, it makes it easier this way.

Regarding the output node, I think the best way be to not change the ouput node at all, but create a completely new node called ResourceSaver (or anything else, I'm not good at naming things).
This one takes the node input and the string input in your preferred order and you save the scene from there. This way it doesn't break backward compatibility and it doesn't force the feature to be always on, people can just add the node if they need it.

**Comment by christinoleo** [comment]
Ah, ok! I will split the PR then. Sorry for merging all here btw, it was actually by mistake.

Good idea on the new node for ResourceSaver! Will do that.

**Comment by HungryProton** [comment]
Thanks! Merging the search node feature

**Pull request merged**
