### PR TITLE
Merge Surfaces feature + example tweaks

### PR DESCRIPTION
**Pull request by BryceBubbles**
Hey,
I've got the `Merge Surfaces` feature working for the `Merge Meshes` node, with an added checkbox input.

I also changed the MESH inputs to NODE_3D and used a modifed `_get_mesh_from_node` function from `make_multimesh` which should return all MeshInstances, including multiple children.

Merging surfaces currently tries to merge in these mesh arrays:
- ARRAY_NORMAL
- ARRAY_INDEX
- ARRAY_COLOR
- ARRAY_TEX_UV
- ARRAY_TEX_UV2

But I'm not sure how to handle the case where you try to merge surfaces where some are indexed and some aren't, or some have UVs and some don't etc. I can work on this, but what's your thoughts?

I also added handling for multiple materials, by checking all three slots (material override, instance surface, mesh surface) and applying the found material to the meshes surface. This way you can later merge multiple meshes and have them keep their materials.

So to show all this off a bit more I added a new example based on simple_tree. It merges the trunk/branches with the leaves and generates a MultiMesh forest with the final mesh.

I also added a ground plane and tweaked the grass material colors a bit.
See what you think, and feel free to ditch any of those cosmetic changes.

Also, let me know if I've done this pull request right, as it's my first time doing it :o

### CODE REVIEW

**Comment by BryceBubbles** [comment]
I modified the `generic_input` node so that a `ConceptGraph` as an input will return it's `output` Spatial. Allows us to make things a bit more modular. So my Forest example now has a Forest graph with the Tree graph as an input.

**Comment by HungryProton** [comment]
Hey! Sorry I took some time to answer.

A lot of the meshes operations are being moved to gdnative, same for other heavy operations that are not really suited for gdscript. It's taking a bit of time though but I need to get it sorted before moving on to the next release. There's an existing library that takes care of merging surfaces sorted by material I'm trying to get to work.

I like the idea of nesting other graphs though, I think it should be in its own node to enable more options like automation in the future (generating more variants from another graph). Maybe this should be in its own PR, that makes things easier to review

**Comment by BryceBubbles** [comment]
Oh ok, that would have been good to know the other day when I mentioned I was working on this. Maybe you didn't catch that? I'd like to contribute if I can, but there's no point in doubling up work on a similar feature.

The performance of merging meshes in GDscript is definitely not amazing, but it's not horrible for small things like the simple tree example. Definitely looking forward to testing out your GDnative implementation though :)

---
I also just started working on a `Plane mesh from transforms` node and a `Position from noise` node that allows making simple terrains from a point grid + noise.
**But perhaps that's something you'd want done in GDnative as well?**
**Would it be worth my while to still work on the node logic in GDscript, and then the mesh generation can be moved to GDnative later?**
I've been meaning to get into GDnative, but every time I look into it, I immediately get a headache (joking).

---
As for the ConceptGraph nesting, yes a more complete system that allows making variants from another graph would be good. My idea was just to use duplicate ConceptGraph nodes as inputs and change their template properties in the inspector.

**I can do a separate PR of this, but it was just a simple 2 line type check, so it's probably not worth it?**
**I could work on a more complete feature for this if you want?**
But I'm not totally sure what you're thinking here, and perhaps it's best left to you?

---
Let me know about the questions in bold!
Cheers

**Comment by HungryProton** [comment]
Sorry I didn't understood you were working on it, I'll be more careful next time. 

Porting gdscript that already exists to gdnative is rather quick though so don't worry about making a node in gdscript first. Unless the performance is really bad, only a few of them will ever be ported to c++ anyway.
Merging surfaces is a bit special because the gdnative library just happened to already exist so we may as well reuse it instead of rewriting everything.

***

As far as I know, nobody is working on terrain nodes yet. (It's somewhere down in my todo list but there's so many things to do before).
I like the idea of a `Position from noise` node but I'm worried about how `Plane Mesh from Transforms` would work? 
Does it needs a perfectly aligned grid of transforms to generate a terrain? 
What happens if the user provides a random set of transforms? 
If that's the case, maybe this node should take a noise input directly instead of a set of transforms?

***

As for ConceptGraph nesting, I'm open to suggestions because I'm not really sure what would benefit the most to people. A few options include : 
- Only exposing the end result to the graph, in that case your extra check is enough
- Creating a new GraphNode with input slots matching what the nested graph exposes to the inspector. Not entirely sure how hard it might be or how it would be used though.
- Something else entirely?

Your forest example, it duplicates the same tree over and over, but what if you wanted to create a forest filled with different unique trees for example? (Which means no multimesh anymore but that's not the point)
The seed parameter would need to be exposed somehow and telling the main graph to regenerate the nested graph x amount of times requires more nodes and I don't know which ones yet.

Anyway, we don't need to solve everything in one go, if you want to make a PR for what you've already done go for it !

**Comment by BryceBubbles** [comment]
Cool cool cool...
I'm going to open new issues for each of the topics we're discussing here.
I'll post links to those here for

**Comment by BryceBubbles** [comment]
@HungryProton I've opened new issues for each of the topics we're discussing here:

Plane mesh terrain: https://github.com/HungryProton/concept_graph/issues/66
Position from noise: https://github.com/HungryProton/concept_graph/issues/65
ConceptGraph nesting: https://github.com/HungryProton/concept_graph/issues/67

**As for my forest example:**
Duplicating only a couple of tree meshes (and GPU instancing each type) is the common way to generate dense forests in a performant way right? So that's what I was going for there.

Having unique trees is nice, and there's plenty of use cases for that, but dense forests that are performant on lower end hardware isn't one of them.

Another solution I entertained based on the simple tree example, was to batch the leaves of multiple unique trees into the same multi-mesh. Then perhaps doing the same with just a couple of branches that get moved to different points on a couple of different trunks.

I haven't tried this out yet though, as I'm unsure how to go about it - any thoughts?

**Comment by HungryProton** [comment]
Oh definitely, no game tries to have a unique tree in a forest, that was just an example for a use case that may come someday.

Also, I'm sorry I dragged this for so long, but I'm still going to merge you PR, the gdnative part is causing me a lot of issues on the cross compilation part and there's no point adding a feature that only works on one OS and not on the others. Since I don't know how long it will take me to fix it (or even if I ever manage to fix it some day), it's best if you work can be merged in the meantime.


One last thing (that's more about scene management and not the add-on itself), if only a part of the multimesh is visible on screen, the whole thing is rendered, including what's not in the camera field of view, so if you're making a 4km x 4km forest, it's best to split it in smaller chunks because the renderer wont make that optimization for you.

**Comment by BryceBubbles** [comment]
Gdnative sure does seem to be a pain to work with! And yeah not having cross compilation would suck for a plugin. 

While it would be sweet to have that performance gain, I'm glad my work on this can be useful for a bit. 

There's possibly some tweaks to be made that might improve performance of this gdscript mesh merging too, so I'll take a look at that some time.

Multimesh - yeah I'm aware there's a balancing act between instancing and frustrum culling. For the past few months I've been working on infinite procedural terrain (like so many do), and trying to keep decent fps when rendering lush grass and lots of trees, all on a laptop with integrated graphics... so yeah I'm very aware. ;)

**Comment by HungryProton** [comment]
I can take a look at the optimizations myself if you want. For now, having something that works is more important than having something fast.

(For grass specifically, if your integrated graphic card supports particle shaders, that's probably the faster option)

**Comment by BryceBubbles** [comment]
Sure go for it with the optimizations.

**Particle shaders**
Oh yup, but that requires using heightmaps right? 
So far I've been generating procedural meshes, not heightmaps, as gdscript is slower at generating images from the same amount of points.

I did get simplex noise working in a canvas shader, running in a viewport, which output normalmaps with the heights saved in the alpha channel. Which I then use in a vertex shader on an infinite grid of plane meshes.

That was pretty fast, but all terrain shape logic had to be in the canvas shader, which wasn't very flexible, as well as other issues. 

But yeah generating proper meshes has worked out best for me so far.

**Pull request merged**
